#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 with roundrobin algorithm
apt-get update -y
apt-get install haproxy -y

cat > /etc/haproxy/haproxy.cfg << 'EOF'
global
    log /dev/log local0
    maxconn 2048
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7063-web-01 44.201.204.119:80 check
    server 7063-web-02 3.91.200.7:80 check
EOF

service haproxy restart