#!/usr/bin/env bash
# Installs and configures nginx web server on Ubuntu
apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html

service nginx start