#!/usr/bin/env bash
# Configures nginx with a 301 redirect for /redirect_me
apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '24i\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart